### ISSUE TITLE
Usage of Cache.bytesOut and bytesIn looks racy

### ISSUE THREAD

**Issue by bep** [alexandres/poormanscdn#10]
I'm pretty sure that the Go race detector will complain if you put some realistic load on it.

**Comment by alexandres** [comment]
Yes, should use a channel instead like is one with the `FreeSpaceWatchdog`. I'll fix this.

**Comment by alexandres** [comment]
Fixed in https://github.com/alexandres/poormanscdn/commit/29a7141d566f06c839bb8929f827d5a186e0908f 

Perhaps use Channels instead in the future but for this simple case atomics seem fine.
