### ISSUE TITLE
Host StorageProvider lookup includes port if not using :80 or :443

### ISSUE THREAD

**Issue by alexandres** [alexandres/poormanscdn#14]
@bep 

When running a local server with `Listen` set to `:8080` and `"Hosts": {  "localhost": ... }`, the StorageProvider lookup fails. Changing to `"Hosts": {  "localhost:8080": ... }` makes it work.

Since all `Hosts` share the same port, this is unnecessary. 

I changed this in commit https://github.com/alexandres/poormanscdn/commit/cc5851e3857df138fce8690c896a694e589368cf

**Comment by bep** [comment]
Didn't test that. On a side note, I really like how easy https/virtual hosts looks in the updated README.

Re. the config examples, I assume that you know that this:

```json
"Hosts": { 
	"myblog.com": { "Bucket": "blogs", "Path": "my", "AccessKey": "", "SecretKey": "" },
	"familyblog.com": { "Bucket": "blogs", "Path": "family", "AccessKey": "", "SecretKey": "" },
	"carrentals.com": { "Bucket": "carrentals", "Path": "", "AccessKey": "", "SecretKey": "" }
}
```

Is the same as:

```json
"Hosts": { 
	"myblog.com": { "Bucket": "blogs", "Path": "my" },
	"familyblog.com": { "Bucket": "blogs", "Path": "family" },
	"carrentals.com": { "Bucket": "carrentals" }
}
```

I know it us useful to show and explain all options in one section, but the above does look better in this concrete example.
