### ISSUE TITLE
Write of stale file after Delete

### ISSUE THREAD

**Issue by alexandres** [alexandres/poormanscdn#18]
As there is no locking, the following could happen with a file `A`:

1. Download of file `Av1` not in cache is initiated by client 1.
2. Cache owner issues delete of `Av1`. `Av1` is deleted from cache. `Av2` is now available on origin.
3. Download of file `Av1` completes and is written to cache.
4. If client 2 requests file `A`, he will be served the stale file `Av1`, rather than the server retrieving newer version `Av2`.

Step 3. above must fail. 

A possible solution is to record the start time of 1. and  deletion time of 2. and compare them before writing to the cache.

Suggestions are welcome!

Note: This is inline with issue #17 where the lack of locking causes problems, but this case is more severe. If you are aware of any other issues cause by the lack of locks, please comment here.

**Comment by bep** [comment]
>A possible solution is to record the start time of 1. and deletion time of 2. and compare them before writing to the cache.

As this will be a rare thing I would suggest you do this optimistic locking on the cache level and not individual files: Set a timestamp on any delete from cache and do not accept any writes started before that time. You would need a mutex to set and check that value.

**Comment by alexandres** [comment]
I agree that doing it at the cache level suffices. I will implement this tomorrow.

**Comment by alexandres** [comment]
Fixed in https://github.com/alexandres/poormanscdn/commit/19c530961f6bbf3fba060d2def6f110522f44624
